/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  User,
  UserRole,
  OrgLevel,
  StateNode,
  DistrictNode,
  ChapterNode,
  AccountHead,
  HeadType,
  Transaction,
  Asset,
  BankBalance,
  ChapterMaster,
  Member,
} from "./types";

// Database Version Key - Incrementing this forces fresh seed data loading
export const CURRENT_DB_VERSION = "v5_rich_seed_2026";

// Organizational hierarchy nodes
export const STATES: StateNode[] = [
  { id: "kerala", name: "Kerala" },
  { id: "tamil_nadu", name: "Tamil Nadu" },
  { id: "karnataka", name: "Karnataka" },
];

export const DISTRICTS: DistrictNode[] = [
  // Kerala districts
  { id: "ernakulam", name: "Ernakulam", stateId: "kerala" },
  { id: "kozhikode", name: "Kozhikode", stateId: "kerala" },
  // Tamil Nadu districts
  { id: "chennai", name: "Chennai", stateId: "tamil_nadu" },
  // Karnataka districts
  { id: "bangalore", name: "Bangalore Rural", stateId: "karnataka" },
];

export const CHAPTERS: ChapterNode[] = [
  // Ernakulam chapters
  { id: "cochin", name: "Cochin Chapter", districtId: "ernakulam" },
  { id: "aluva", name: "Aluva Chapter", districtId: "ernakulam" },
  // Kozhikode chapters
  { id: "calicut_city", name: "Calicut City", districtId: "kozhikode" },
  { id: "vadakara", name: "Vadakara Chapter", districtId: "kozhikode" },
  // Chennai chapters
  { id: "chennai_central", name: "Chennai Central", districtId: "chennai" },
  { id: "chennai_south", name: "Chennai South", districtId: "chennai" },
  // Bangalore chapters
  { id: "bangalore_north", name: "Bangalore North", districtId: "bangalore" },
];

// Default Account Heads
export const DEFAULT_ACCOUNT_HEADS: AccountHead[] = [
  // Income Heads
  { id: "inc_sponsorship", name: "Sponsorship", type: HeadType.Income, isSystem: true, isActive: true },
  { id: "inc_donations", name: "Donations", type: HeadType.Income, isSystem: true, isActive: true },
  { id: "inc_coaching", name: "Coaching programs", type: HeadType.Income, isSystem: true, isActive: true },
  { id: "inc_profit_share", name: "Profit Share", type: HeadType.Income, isSystem: true, isActive: true },
  { id: "inc_bank", name: "Bank income", type: HeadType.Income, isSystem: true, isActive: true },
  { id: "inc_member_ordinary", name: "Membership - ordinary", type: HeadType.Income, isSystem: true, isActive: true },
  { id: "inc_member_gold", name: "Membership - gold", type: HeadType.Income, isSystem: true, isActive: true },
  { id: "inc_member_platinum", name: "Membership - platinum", type: HeadType.Income, isSystem: true, isActive: true },

  // Expense Heads
  { id: "exp_tada", name: "TA&DA", type: HeadType.Expense, isSystem: true, isActive: true },
  { id: "exp_meeting", name: "Meeting expense", type: HeadType.Expense, isSystem: true, isActive: true },
  { id: "exp_printing", name: "Printing", type: HeadType.Expense, isSystem: true, isActive: true },
  { id: "exp_postage", name: "Postage", type: HeadType.Expense, isSystem: true, isActive: true },
  { id: "exp_digital_media", name: "Digital media", type: HeadType.Expense, isSystem: true, isActive: true },
  { id: "exp_bank", name: "Bank expense", type: HeadType.Expense, isSystem: true, isActive: true },
];

// Predefined Users
export const USERS: User[] = [
  {
    username: "admin",
    name: "System Admin",
    role: UserRole.Admin,
    level: OrgLevel.National,
    designation: "Administrator",
    password: "admin",
  },
  {
    username: "national_pres",
    name: "Dr. K. S. Menon",
    role: UserRole.President,
    level: OrgLevel.National,
    designation: "National President",
    password: "pass",
  },
  {
    username: "national_treas",
    name: "Dr. Sandeep Kumar",
    role: UserRole.Treasurer,
    level: OrgLevel.National,
    designation: "National Treasurer",
    password: "pass",
  },
  {
    username: "kerala_sec",
    name: "Dr. Faisal Rahman",
    role: UserRole.Secretary,
    level: OrgLevel.State,
    nodeId: "kerala",
    designation: "Kerala State Secretary",
    password: "pass",
  },
  {
    username: "kerala_treas",
    name: "Dr. Mini Joseph",
    role: UserRole.Treasurer,
    level: OrgLevel.State,
    nodeId: "kerala",
    designation: "Kerala State Treasurer",
    password: "pass",
  },
  {
    username: "ekm_president",
    name: "Dr. George Paul",
    role: UserRole.President,
    level: OrgLevel.District,
    nodeId: "ernakulam",
    designation: "Ernakulam District President",
    password: "pass",
  },
  {
    username: "cochin_treasurer",
    name: "Dr. Basheer",
    role: UserRole.Treasurer,
    level: OrgLevel.Local,
    nodeId: "cochin",
    designation: "Cochin Chapter Treasurer",
    password: "pass",
  },
  {
    username: "cochin_member",
    name: "Dr. Smitha Sen",
    role: UserRole.GeneralUser,
    level: OrgLevel.Local,
    nodeId: "cochin",
    designation: "Cochin Chapter Member",
    password: "pass",
  },
  {
    username: "aluva_treasurer",
    name: "Dr. Abraham Mathew",
    role: UserRole.Treasurer,
    level: OrgLevel.Local,
    nodeId: "aluva",
    designation: "Aluva Chapter Treasurer",
    password: "pass",
  },
  {
    username: "chennai_treasurer",
    name: "Dr. R. Ramanujan",
    role: UserRole.Treasurer,
    level: OrgLevel.Local,
    nodeId: "chennai_central",
    designation: "Chennai Central Treasurer",
    password: "pass",
  },
];

// Sheet 1: Assets Master Register
export const PRELOADED_ASSETS: Asset[] = [
  {
    slNo: 1,
    id: "ast_1",
    date: "2024-05-10",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    assetId: "AST-[#001]",
    assetName: "High-Lumen 4K Laser Projector & Sound System",
    purchaseDate: "2024-05-05",
    assetValue: 55000,
    category: "Electronics",
    assetLife: 5,
    custodianName: "Dr. Basheer",
  },
  {
    slNo: 2,
    id: "ast_2",
    date: "2024-08-20",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    assetId: "AST-[#002]",
    assetName: "Executive Conference Table & 16 Ergonomic Chairs",
    purchaseDate: "2024-08-15",
    assetValue: 42000,
    category: "Furniture",
    assetLife: 10,
    custodianName: "Dr. Basheer",
  },
  {
    slNo: 3,
    id: "ast_3",
    date: "2025-01-15",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    assetId: "AST-[#003]",
    assetName: "Digital Health Kiosk & Diagnostic Touch Monitor",
    purchaseDate: "2025-01-10",
    assetValue: 85000,
    category: "Medical Equipment",
    assetLife: 7,
    custodianName: "Dr. Abraham Mathew",
  },
  {
    slNo: 4,
    id: "ast_4",
    date: "2025-04-10",
    chapterIdInput: "KL-KZ-CC01",
    chapterNameInput: "Calicut City",
    assetId: "AST-[#004]",
    assetName: "Office Workstation Laptops (2 Units)",
    purchaseDate: "2025-04-05",
    assetValue: 125000,
    category: "Electronics",
    assetLife: 4,
    custodianName: "Dr. Faisal Rahman",
  },
  {
    slNo: 5,
    id: "ast_5",
    date: "2025-08-05",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    assetId: "AST-[#005]",
    assetName: "Heavy-Duty Laser Printer & Document Scanner",
    purchaseDate: "2025-08-01",
    assetValue: 32000,
    category: "Office Electronics",
    assetLife: 4,
    custodianName: "Dr. R. Ramanujan",
  },
  {
    slNo: 6,
    id: "ast_6",
    date: "2025-11-12",
    chapterIdInput: "DL-ND-HQ00",
    chapterNameInput: "National Headquarters",
    assetId: "AST-[#006]",
    assetName: "Solar Inverter & Tubular Battery System",
    purchaseDate: "2025-11-08",
    assetValue: 68000,
    category: "Electrical Equipment",
    assetLife: 8,
    custodianName: "Dr. Sandeep Kumar",
  },
  {
    slNo: 7,
    id: "ast_7",
    date: "2026-02-01",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    assetId: "AST-[#007]",
    assetName: "2-Ton Inverter Air Conditioner Unit",
    purchaseDate: "2026-01-28",
    assetValue: 46000,
    category: "Appliances",
    assetLife: 6,
    custodianName: "Dr. Basheer",
  },
  {
    slNo: 8,
    id: "ast_8",
    date: "2026-04-20",
    chapterIdInput: "KA-BN-BN01",
    chapterNameInput: "Bangalore North",
    assetId: "AST-[#008]",
    assetName: "Medical Reference Library Cabinet & Rare Books",
    purchaseDate: "2026-04-15",
    assetValue: 28000,
    category: "Furniture",
    assetLife: 15,
    custodianName: "Dr. Ananya Sharma",
  },
];

// Sheet 2: FD & Bank Balances
export const PRELOADED_BANK_BALANCES: BankBalance[] = [
  {
    slNo: 1,
    id: "bank_1",
    date: "2026-06-30",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    amountType: "Bank Balance",
    amount: 385000,
  },
  {
    slNo: 2,
    id: "bank_2",
    date: "2026-06-30",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    amountType: "FD",
    amount: 800000,
  },
  {
    slNo: 3,
    id: "bank_3",
    date: "2026-06-30",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    amountType: "Bank Balance",
    amount: 245000,
  },
  {
    slNo: 4,
    id: "bank_4",
    date: "2026-06-30",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    amountType: "FD",
    amount: 500000,
  },
  {
    slNo: 5,
    id: "bank_5",
    date: "2026-06-30",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    amountType: "Bank Balance",
    amount: 412000,
  },
  {
    slNo: 6,
    id: "bank_6",
    date: "2026-06-30",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    amountType: "FD",
    amount: 1000000,
  },
  {
    slNo: 7,
    id: "bank_7",
    date: "2026-06-30",
    chapterIdInput: "KL-KZ-CC01",
    chapterNameInput: "Calicut City",
    amountType: "Bank Balance",
    amount: 290000,
  },
  {
    slNo: 8,
    id: "bank_8",
    date: "2026-06-30",
    chapterIdInput: "KL-KZ-CC01",
    chapterNameInput: "Calicut City",
    amountType: "FD",
    amount: 600000,
  },
  {
    slNo: 9,
    id: "bank_9",
    date: "2026-06-30",
    chapterIdInput: "DL-ND-HQ00",
    chapterNameInput: "National Headquarters",
    amountType: "Bank Balance",
    amount: 1850000,
  },
  {
    slNo: 10,
    id: "bank_10",
    date: "2026-06-30",
    chapterIdInput: "DL-ND-HQ00",
    chapterNameInput: "National Headquarters",
    amountType: "FD",
    amount: 3500000,
  },
];

// Sheet 3: Chapter Master Directory
export const PRELOADED_CHAPTER_DIRECTORY: ChapterMaster[] = [
  {
    slNo: 1,
    id: "KL-EK-CO01",
    chapterName: "Cochin Chapter",
    entityType: "Local Chapter",
    state: "Kerala",
    district: "Ernakulam",
    chapterAddress: "IHMA House, MG Road, Ernakulam, Cochin - 682011",
    presidentId: "MEM-KRL-101",
    presidentName: "Dr. George Paul",
    vpId: "MEM-KRL-102",
    vpName: "Dr. Joseph Kurian",
    secretaryId: "MEM-KRL-103",
    secretaryName: "Dr. Smitha Sen",
    treasurerId: "MEM-KRL-104",
    treasurerName: "Dr. Basheer",
    contactNo: "+91 98470 12345",
    whatsappNo: "+91 98470 12345",
    officeNo: "0484 2356789",
    email: "cochin@ihma.in",
    formationDate: "2010-04-15",
  },
  {
    slNo: 2,
    id: "KL-EK-AL02",
    chapterName: "Aluva Chapter",
    entityType: "Local Chapter",
    state: "Kerala",
    district: "Ernakulam",
    chapterAddress: "Subhash Nagar, Near Bank Junction, Aluva - 683101",
    presidentId: "MEM-KRL-201",
    presidentName: "Dr. Roy Antony",
    vpId: "MEM-KRL-202",
    vpName: "Dr. Thomas Mathew",
    secretaryId: "MEM-KRL-203",
    secretaryName: "Dr. Anil Varghese",
    treasurerId: "MEM-KRL-204",
    treasurerName: "Dr. Abraham Mathew",
    contactNo: "+91 98471 23456",
    whatsappNo: "+91 98471 23456",
    officeNo: "0484 2623456",
    email: "aluva@ihma.in",
    formationDate: "2012-08-20",
  },
  {
    slNo: 3,
    id: "KL-KZ-CC01",
    chapterName: "Calicut City",
    entityType: "Local Chapter",
    state: "Kerala",
    district: "Kozhikode",
    chapterAddress: "Mavoor Road Junction, Calicut - 673001",
    presidentId: "MEM-KZ-401",
    presidentName: "Dr. Faisal Rahman",
    vpId: "MEM-KZ-402",
    vpName: "Dr. N. P. Unnikrishnan",
    secretaryId: "MEM-KZ-403",
    secretaryName: "Dr. Sujith Kumar",
    treasurerId: "MEM-KZ-404",
    treasurerName: "Dr. K. P. Abdullah",
    contactNo: "+91 98472 34567",
    whatsappNo: "+91 98472 34567",
    officeNo: "0495 2721234",
    email: "calicut@ihma.in",
    formationDate: "2011-02-10",
  },
  {
    slNo: 4,
    id: "TN-CN-CC01",
    chapterName: "Chennai Central",
    entityType: "Local Chapter",
    state: "Tamil Nadu",
    district: "Chennai",
    chapterAddress: "22 Anna Salai, Thousand Lights, Chennai - 600006",
    presidentId: "MEM-TN-301",
    presidentName: "Dr. Vijay Balaji",
    vpId: "MEM-TN-302",
    vpName: "Dr. K. Swaminathan",
    secretaryId: "MEM-TN-303",
    secretaryName: "Dr. S. Sundaram",
    treasurerId: "MEM-TN-304",
    treasurerName: "Dr. R. Ramanujan",
    contactNo: "+91 98400 34567",
    whatsappNo: "+91 98400 34567",
    officeNo: "044 28291000",
    email: "chennai.central@ihma.in",
    formationDate: "2008-11-05",
  },
  {
    slNo: 5,
    id: "KA-BN-BN01",
    chapterName: "Bangalore North",
    entityType: "Local Chapter",
    state: "Karnataka",
    district: "Bangalore Rural",
    chapterAddress: "12th Cross, Indiranagar, Bangalore - 560038",
    presidentId: "MEM-KA-501",
    presidentName: "Dr. Suresh Hedge",
    vpId: "MEM-KA-502",
    vpName: "Dr. Preeti Gowda",
    secretaryId: "MEM-KA-503",
    secretaryName: "Dr. Ananya Sharma",
    treasurerId: "MEM-KA-504",
    treasurerName: "Dr. M. N. Rao",
    contactNo: "+91 98800 56789",
    whatsappNo: "+91 98800 56789",
    officeNo: "080 25219900",
    email: "bangalore.north@ihma.in",
    formationDate: "2015-06-12",
  },
  {
    slNo: 6,
    id: "DL-ND-HQ00",
    chapterName: "National Headquarters",
    entityType: "National Chapter",
    state: "Delhi",
    district: "New Delhi",
    chapterAddress: "IHMA National Bhavan, Janakpuri, New Delhi - 110058",
    presidentId: "MEM-NAT-001",
    presidentName: "Dr. K. S. Menon",
    vpId: "MEM-NAT-002",
    vpName: "Dr. Ramesh Chandra",
    secretaryId: "MEM-NAT-003",
    secretaryName: "Dr. P. K. Sharma",
    treasurerId: "MEM-NAT-004",
    treasurerName: "Dr. Sandeep Kumar",
    contactNo: "+91 98100 99999",
    whatsappNo: "+91 98100 99999",
    officeNo: "011 25501234",
    email: "hq@ihma.in",
    formationDate: "1998-01-26",
  },
];

// Sheet 7: Member Directory (All prefixed with Dr. )
export const PRELOADED_MEMBERS: Member[] = [
  {
    slNo: 1,
    id: "mem_1",
    memberId: "MEM-KRL-101",
    memberName: "Dr. George Paul",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    qualification: "MD(Hom) in Materia Medica",
    membershipType: "Platinum",
    membershipDate: "2022-04-10",
    membershipStatus: "Active",
    mobileNumber: "+91 98470 11111",
    whatsappNumber: "+91 98470 11111",
    email: "dr.georgepaul@gmail.com",
    clinicNumber: "0484 2300111",
    gender: "Male",
    bloodGroup: "O+",
    specialization: "Pediatric Homoeopathy",
    clinicAddress: "Paul Clinic, MG Road, Ernakulam",
  },
  {
    slNo: 2,
    id: "mem_2",
    memberId: "MEM-KRL-102",
    memberName: "Dr. Joseph Kurian",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    qualification: "BHMS (Kerala Univ)",
    membershipType: "Gold",
    membershipDate: "2022-08-15",
    membershipStatus: "Active",
    mobileNumber: "+91 98470 22111",
    whatsappNumber: "+91 98470 22111",
    email: "dr.kurian@yahoo.com",
    clinicNumber: "0484 2300222",
    gender: "Male",
    bloodGroup: "A+",
    specialization: "Skin & Allergy Care",
    clinicAddress: "Kurian Homeo Center, Edappally, Cochin",
  },
  {
    slNo: 3,
    id: "mem_3",
    memberId: "MEM-KRL-103",
    memberName: "Dr. Smitha Sen",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    qualification: "BHMS, MD(Hom)",
    membershipType: "Silver",
    membershipDate: "2023-01-20",
    membershipStatus: "Active",
    mobileNumber: "+91 98470 33222",
    whatsappNumber: "+91 98470 33222",
    email: "dr.smithasen@gmail.com",
    clinicNumber: "0484 2300333",
    gender: "Female",
    bloodGroup: "B+",
    specialization: "Gynaecology & Endocrine",
    clinicAddress: "Sen Homoeo Care, Kadavanthra, Cochin",
  },
  {
    slNo: 4,
    id: "mem_4",
    memberId: "MEM-KRL-104",
    memberName: "Dr. Basheer",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    qualification: "BHMS, TCMC Reg No 11402",
    membershipType: "Gold",
    membershipDate: "2023-03-12",
    membershipStatus: "Active",
    mobileNumber: "+91 98470 44333",
    whatsappNumber: "+91 98470 44333",
    email: "dr.basheer@yahoo.com",
    clinicNumber: "0484 2300444",
    gender: "Male",
    bloodGroup: "O+",
    specialization: "General Practice & Lifestyle",
    clinicAddress: "Al Shifa Homeo Clinic, Vyttila, Cochin",
  },
  {
    slNo: 5,
    id: "mem_5",
    memberId: "MEM-KRL-201",
    memberName: "Dr. Roy Antony",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    qualification: "MD(Hom) Organon of Medicine",
    membershipType: "Platinum",
    membershipDate: "2022-10-05",
    membershipStatus: "Active",
    mobileNumber: "+91 98471 55444",
    whatsappNumber: "+91 98471 55444",
    email: "dr.royantony@gmail.com",
    clinicNumber: "0484 2620555",
    gender: "Male",
    bloodGroup: "AB+",
    specialization: "Chronic Rheumatoid Care",
    clinicAddress: "Antony Homeo Hospital, Bank Junction, Aluva",
  },
  {
    slNo: 6,
    id: "mem_6",
    memberId: "MEM-KRL-202",
    memberName: "Dr. Thomas Mathew",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    qualification: "BHMS, MSc Clinical Psychology",
    membershipType: "Gold",
    membershipDate: "2023-05-18",
    membershipStatus: "Active",
    mobileNumber: "+91 98471 66555",
    whatsappNumber: "+91 98471 66555",
    email: "dr.thomasm@gmail.com",
    clinicNumber: "0484 2620666",
    gender: "Male",
    bloodGroup: "O-",
    specialization: "Mind-Body Medicine",
    clinicAddress: "St. Thomas Clinic, Subhash Nagar, Aluva",
  },
  {
    slNo: 7,
    id: "mem_7",
    memberId: "MEM-KRL-203",
    memberName: "Dr. Anil Varghese",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    qualification: "BHMS",
    membershipType: "Silver",
    membershipDate: "2023-11-22",
    membershipStatus: "Active",
    mobileNumber: "+91 98471 77666",
    whatsappNumber: "+91 98471 77666",
    email: "dr.anilvarghese@gmail.com",
    clinicNumber: "0484 2620777",
    gender: "Male",
    bloodGroup: "A+",
    specialization: "Respiratory & Asthma",
    clinicAddress: "Varghese Clinic, Perumbavoor Road, Aluva",
  },
  {
    slNo: 8,
    id: "mem_8",
    memberId: "MEM-KRL-204",
    memberName: "Dr. Abraham Mathew",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    qualification: "BHMS, MSc (Research)",
    membershipType: "Gold",
    membershipDate: "2024-01-14",
    membershipStatus: "Active",
    mobileNumber: "+91 98471 88777",
    whatsappNumber: "+91 98471 88777",
    email: "dr.abraham.m@gmail.com",
    clinicNumber: "0484 2620888",
    gender: "Male",
    bloodGroup: "B+",
    specialization: "Gastroenterology",
    clinicAddress: "Mathew Homeo Clinic, Aluva",
  },
  {
    slNo: 9,
    id: "mem_9",
    memberId: "MEM-TN-301",
    memberName: "Dr. Vijay Balaji",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    qualification: "MD(Hom), PhD",
    membershipType: "Platinum",
    membershipDate: "2021-06-10",
    membershipStatus: "Active",
    mobileNumber: "+91 98400 99888",
    whatsappNumber: "+91 98400 99888",
    email: "dr.vijaybalaji@chennaihomoeo.org",
    clinicNumber: "044 28290999",
    gender: "Male",
    bloodGroup: "O+",
    specialization: "Oncology Supportive Care",
    clinicAddress: "Balaji Homoeo Research Institute, Anna Salai, Chennai",
  },
  {
    slNo: 10,
    id: "mem_10",
    memberId: "MEM-TN-302",
    memberName: "Dr. K. Swaminathan",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    qualification: "BHMS, TNC Medical Council",
    membershipType: "Gold",
    membershipDate: "2022-09-25",
    membershipStatus: "Active",
    mobileNumber: "+91 98400 11222",
    whatsappNumber: "+91 98400 11222",
    email: "dr.swaminathan@gmail.com",
    clinicNumber: "044 28291122",
    gender: "Male",
    bloodGroup: "A+",
    specialization: "Rheumatology",
    clinicAddress: "Swami Homeo Clinic, Mylapore, Chennai",
  },
  {
    slNo: 11,
    id: "mem_11",
    memberId: "MEM-TN-303",
    memberName: "Dr. S. Sundaram",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    qualification: "BHMS",
    membershipType: "General",
    membershipDate: "2023-07-30",
    membershipStatus: "Active",
    mobileNumber: "+91 98400 22333",
    whatsappNumber: "+91 98400 22333",
    email: "dr.sundaram@gmail.com",
    clinicNumber: "044 28292233",
    gender: "Male",
    bloodGroup: "B+",
    specialization: "General Practice",
    clinicAddress: "Sundaram Clinic, T.Nagar, Chennai",
  },
  {
    slNo: 12,
    id: "mem_12",
    memberId: "MEM-TN-304",
    memberName: "Dr. R. Ramanujan",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    qualification: "BHMS, MD(Hom)",
    membershipType: "Gold",
    membershipDate: "2024-02-18",
    membershipStatus: "Active",
    mobileNumber: "+91 98400 33444",
    whatsappNumber: "+91 98400 33444",
    email: "dr.ramanujan@gmail.com",
    clinicNumber: "044 28293344",
    gender: "Male",
    bloodGroup: "AB+",
    specialization: "Cardiology Supportive",
    clinicAddress: "Ramanujan Homeo Center, Thousand Lights, Chennai",
  },
  {
    slNo: 13,
    id: "mem_13",
    memberId: "MEM-KZ-401",
    memberName: "Dr. Faisal Rahman",
    chapterIdInput: "KL-KZ-CC01",
    chapterNameInput: "Calicut City",
    qualification: "MD(Hom) Repertory",
    membershipType: "Platinum",
    membershipDate: "2020-05-12",
    membershipStatus: "Active",
    mobileNumber: "+91 98472 44555",
    whatsappNumber: "+91 98472 44555",
    email: "dr.faisalrahman@gmail.com",
    clinicNumber: "0495 2724455",
    gender: "Male",
    bloodGroup: "O+",
    specialization: "Renal & Kidney Stones",
    clinicAddress: "Rahman Homeo Specialty Clinic, Mavoor Road, Calicut",
  },
  {
    slNo: 14,
    id: "mem_14",
    memberId: "MEM-NAT-001",
    memberName: "Dr. K. S. Menon",
    chapterIdInput: "DL-ND-HQ00",
    chapterNameInput: "National Headquarters",
    qualification: "MD(Hom), PhD, Former Principal",
    membershipType: "Platinum",
    membershipDate: "2018-01-15",
    membershipStatus: "Active",
    mobileNumber: "+91 98100 88777",
    whatsappNumber: "+91 98100 88777",
    email: "dr.ksmenon@ihma.in",
    clinicNumber: "011 25508877",
    gender: "Male",
    bloodGroup: "A+",
    specialization: "Academic Research & Materia Medica",
    clinicAddress: "Menon Clinical Research, Janakpuri, New Delhi",
  },
  {
    slNo: 15,
    id: "mem_15",
    memberId: "MEM-NAT-002",
    memberName: "Dr. Sandeep Kumar",
    chapterIdInput: "DL-ND-HQ00",
    chapterNameInput: "National Headquarters",
    qualification: "MD(Hom) Pharmacy",
    membershipType: "Gold",
    membershipDate: "2019-08-20",
    membershipStatus: "Active",
    mobileNumber: "+91 98100 77666",
    whatsappNumber: "+91 98100 77666",
    email: "dr.sandeep@ihma.in",
    clinicNumber: "011 25507766",
    gender: "Male",
    bloodGroup: "O+",
    specialization: "Pharmacology & Quality Control",
    clinicAddress: "National Homeo Care, Connaught Place, New Delhi",
  },
];

// Sheets 4, 5, 6: Transaction Ledger
// Note: Income >> Expense, Bank >> Cash
export const PRELOADED_TRANSACTIONS: Transaction[] = [
  // ==================== RECEIPTS / INCOMES (FY 2024, 2025, 2026) ====================
  {
    slNo: 1,
    id: "tx_inc_1",
    date: "2024-04-15",
    type: HeadType.Income,
    headId: "inc_sponsorship",
    headName: "Sponsorship",
    amount: 250000,
    voucherNumber: "RV-24-001",
    description: "Diamond Sponsorship for National Homeopathic Expo 2024",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Willmar Schwabe India Pvt Ltd",
    offeredAmount: 250000,
    paidAmount: 250000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2024-04-15T10:00:00Z",
  },
  {
    slNo: 2,
    id: "tx_inc_2",
    date: "2024-05-20",
    type: HeadType.Income,
    headId: "inc_sponsorship",
    headName: "Sponsorship",
    amount: 120000,
    voucherNumber: "RV-24-002",
    description: "Stall Booking & Branding Sponsorship - Homeo Fair 2024",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "SBL Pharmaceuticals India",
    offeredAmount: 120000,
    paidAmount: 120000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2024-05-20T11:30:00Z",
  },
  {
    slNo: 3,
    id: "tx_inc_3",
    date: "2024-06-10",
    type: HeadType.Income,
    headId: "inc_member_platinum",
    headName: "Membership - platinum",
    amount: 75000,
    voucherNumber: "RV-24-003",
    description: "Platinum Life Membership Fee batch collection (5 Doctors)",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Dr. George Paul & Team",
    paidByMemberId: "MEM-KRL-101",
    offeredAmount: 75000,
    paidAmount: 75000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2024-06-10T14:00:00Z",
  },
  {
    slNo: 4,
    id: "tx_inc_4",
    date: "2024-07-25",
    type: HeadType.Income,
    headId: "inc_cme_delegate",
    headName: "CME Delegate Fees",
    amount: 85000,
    voucherNumber: "RV-24-004",
    description: "Registration fees for Regional CME Seminar on Repertory",
    chapterId: "aluva",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    collectedBy: "Dr. Abraham Mathew",
    paidBy: "Delegate Doctors Association",
    offeredAmount: 90000,
    paidAmount: 85000,
    balanceAmount: 5000,
    paymentMode: "Bank",
    createdBy: "aluva_treasurer",
    createdAt: "2024-07-25T16:15:00Z",
  },
  {
    slNo: 5,
    id: "tx_inc_5",
    date: "2024-09-12",
    type: HeadType.Income,
    headId: "inc_trust_grant",
    headName: "Trust & Grant Income",
    amount: 150000,
    voucherNumber: "RV-24-005",
    description: "Grant received for Clinical Research in Chronic Allergic Care",
    chapterId: "chennai_central",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    collectedBy: "Dr. R. Ramanujan",
    paidBy: "Hahnemann Educational Trust",
    offeredAmount: 150000,
    paidAmount: 150000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "chennai_treasurer",
    createdAt: "2024-09-12T10:45:00Z",
  },
  {
    slNo: 6,
    id: "tx_inc_6",
    date: "2024-11-05",
    type: HeadType.Income,
    headId: "inc_member_gold",
    headName: "Membership - gold",
    amount: 45000,
    voucherNumber: "RV-24-006",
    description: "Gold Membership Dues for 3 newly enrolled doctors",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Dr. Joseph Kurian",
    paidByMemberId: "MEM-KRL-102",
    offeredAmount: 45000,
    paidAmount: 45000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2024-11-05T12:20:00Z",
  },
  {
    slNo: 7,
    id: "tx_inc_7",
    date: "2024-12-18",
    type: HeadType.Income,
    headId: "inc_profit_share",
    headName: "Profit Share",
    amount: 320000,
    voucherNumber: "RV-24-007",
    description: "State Conference 2024 Net Profit Surplus Allocation Share",
    chapterId: "calicut_city",
    chapterIdInput: "KL-KZ-CC01",
    chapterNameInput: "Calicut City",
    collectedBy: "Dr. Faisal Rahman",
    paidBy: "Kerala State Executive Committee",
    offeredAmount: 320000,
    paidAmount: 320000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "kerala_treas",
    createdAt: "2024-12-18T15:30:00Z",
  },
  {
    slNo: 8,
    id: "tx_inc_8",
    date: "2025-01-10",
    type: HeadType.Income,
    headId: "inc_coaching",
    headName: "Coaching programs",
    amount: 95000,
    voucherNumber: "RV-25-001",
    description: "Homoeopathic Medical Officer (HMO) Competitive Coaching Batch 1",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Coaching Enrolled Candidates",
    offeredAmount: 95000,
    paidAmount: 95000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2025-01-10T09:30:00Z",
  },
  {
    slNo: 9,
    id: "tx_inc_9",
    date: "2025-02-14",
    type: HeadType.Income,
    headId: "inc_sponsorship",
    headName: "Sponsorship",
    amount: 180000,
    voucherNumber: "RV-25-002",
    description: "Corporate Equipment Sponsorship for Free Health Camp",
    chapterId: "aluva",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    collectedBy: "Dr. Abraham Mathew",
    paidBy: "Dr. Reckeweg & Co. Germany",
    offeredAmount: 180000,
    paidAmount: 180000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "aluva_treasurer",
    createdAt: "2025-02-14T11:00:00Z",
  },
  {
    slNo: 10,
    id: "tx_inc_10",
    date: "2025-03-22",
    type: HeadType.Income,
    headId: "inc_member_ordinary",
    headName: "Membership - ordinary",
    amount: 35000,
    voucherNumber: "RV-25-003",
    description: "Annual Subscription dues collection batch",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Chapter Member Doctors",
    offeredAmount: 35000,
    paidAmount: 35000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2025-03-22T16:00:00Z",
  },
  {
    slNo: 11,
    id: "tx_inc_11",
    date: "2025-04-18",
    type: HeadType.Income,
    headId: "inc_sponsorship",
    headName: "Sponsorship",
    amount: 200000,
    voucherNumber: "RV-25-004",
    description: "National Academic Symposium Title Sponsorship",
    chapterId: "chennai_central",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    collectedBy: "Dr. R. Ramanujan",
    paidBy: "Medisynth Chemicals Ltd",
    offeredAmount: 200000,
    paidAmount: 200000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "chennai_treasurer",
    createdAt: "2025-04-18T10:00:00Z",
  },
  {
    slNo: 12,
    id: "tx_inc_12",
    date: "2025-05-30",
    type: HeadType.Income,
    headId: "inc_cme_delegate",
    headName: "CME Delegate Fees",
    amount: 110000,
    voucherNumber: "RV-25-005",
    description: "Advanced Homoeopathic Dermatology Workshop Delegate Fees",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Registered Practitioner Doctors",
    offeredAmount: 110000,
    paidAmount: 110000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2025-05-30T14:20:00Z",
  },
  {
    slNo: 13,
    id: "tx_inc_13",
    date: "2025-07-15",
    type: HeadType.Income,
    headId: "inc_member_ordinary",
    headName: "Membership - ordinary",
    amount: 8000,
    voucherNumber: "RV-25-006",
    description: "Spot Cash Membership Subscription collection at monthly meet",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Dr. Smitha Sen",
    paidByMemberId: "MEM-KRL-103",
    offeredAmount: 8000,
    paidAmount: 8000,
    balanceAmount: 0,
    paymentMode: "Cash",
    createdBy: "cochin_treasurer",
    createdAt: "2025-07-15T18:00:00Z",
  },
  {
    slNo: 14,
    id: "tx_inc_14",
    date: "2025-08-20",
    type: HeadType.Income,
    headId: "inc_coaching",
    headName: "Coaching programs",
    amount: 65000,
    voucherNumber: "RV-25-007",
    description: "Post Graduate Entrance Coaching Course Fee",
    chapterId: "aluva",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    collectedBy: "Dr. Abraham Mathew",
    paidBy: "PG Aspirants Batch",
    offeredAmount: 65000,
    paidAmount: 65000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "aluva_treasurer",
    createdAt: "2025-08-20T11:40:00Z",
  },
  {
    slNo: 15,
    id: "tx_inc_15",
    date: "2025-10-10",
    type: HeadType.Income,
    headId: "inc_donations",
    headName: "Donations",
    amount: 100000,
    voucherNumber: "RV-25-008",
    description: "Philanthropic Corpus Fund Donation for Charity Dispensary",
    chapterId: "calicut_city",
    chapterIdInput: "KL-KZ-CC01",
    chapterNameInput: "Calicut City",
    collectedBy: "Dr. Faisal Rahman",
    paidBy: "Malabar Charitable Trust",
    offeredAmount: 100000,
    paidAmount: 100000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "kerala_treas",
    createdAt: "2025-10-10T10:00:00Z",
  },
  {
    slNo: 16,
    id: "tx_inc_16",
    date: "2025-11-28",
    type: HeadType.Income,
    headId: "inc_member_platinum",
    headName: "Membership - platinum",
    amount: 60000,
    voucherNumber: "RV-25-009",
    description: "Platinum Life Membership upgrade collection",
    chapterId: "chennai_central",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    collectedBy: "Dr. R. Ramanujan",
    paidBy: "Dr. Vijay Balaji",
    paidByMemberId: "MEM-TN-301",
    offeredAmount: 60000,
    paidAmount: 60000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "chennai_treasurer",
    createdAt: "2025-11-28T15:10:00Z",
  },
  {
    slNo: 17,
    id: "tx_inc_17",
    date: "2025-12-15",
    type: HeadType.Income,
    headId: "inc_bank",
    headName: "Bank income",
    amount: 38000,
    voucherNumber: "RV-25-010",
    description: "Semi-Annual Fixed Deposit (FD) Interest Credit",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Bank Credit",
    paidBy: "State Bank of India MG Road",
    offeredAmount: 38000,
    paidAmount: 38000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2025-12-15T09:00:00Z",
  },
  {
    slNo: 18,
    id: "tx_inc_18",
    date: "2026-01-20",
    type: HeadType.Income,
    headId: "inc_sponsorship",
    headName: "Sponsorship",
    amount: 300000,
    voucherNumber: "RV-26-001",
    description: "Platinum Title Sponsorship - National Health Congress 2026",
    chapterId: "cochin",
    chapterIdInput: "DL-ND-HQ00",
    chapterNameInput: "National Headquarters",
    collectedBy: "Dr. Sandeep Kumar",
    paidBy: "Bakson Drugs & Pharmaceuticals",
    offeredAmount: 300000,
    paidAmount: 300000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "national_treas",
    createdAt: "2026-01-20T10:00:00Z",
  },
  {
    slNo: 19,
    id: "tx_inc_19",
    date: "2026-02-12",
    type: HeadType.Income,
    headId: "inc_cme_delegate",
    headName: "CME Delegate Fees",
    amount: 90000,
    voucherNumber: "RV-26-002",
    description: "National Clinical Materia Medica Masterclass Registration",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Registered Doctors Batch",
    offeredAmount: 90000,
    paidAmount: 90000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2026-02-12T14:30:00Z",
  },
  {
    slNo: 20,
    id: "tx_inc_20",
    date: "2026-03-25",
    type: HeadType.Income,
    headId: "inc_member_ordinary",
    headName: "Membership - ordinary",
    amount: 22000,
    voucherNumber: "RV-26-003",
    description: "Annual Subscription Dues collection online portal",
    chapterId: "aluva",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    collectedBy: "Dr. Abraham Mathew",
    paidBy: "Dr. Roy Antony & Team",
    paidByMemberId: "MEM-KRL-201",
    offeredAmount: 22000,
    paidAmount: 22000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "aluva_treasurer",
    createdAt: "2026-03-25T11:00:00Z",
  },
  {
    slNo: 21,
    id: "tx_inc_21",
    date: "2026-04-10",
    type: HeadType.Income,
    headId: "inc_sponsorship",
    headName: "Sponsorship",
    amount: 140000,
    voucherNumber: "RV-26-004",
    description: "Annual Official Journal Back Cover Sponsorship",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Lord's Homoeo Laboratory",
    offeredAmount: 140000,
    paidAmount: 140000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2026-04-10T10:30:00Z",
  },
  {
    slNo: 22,
    id: "tx_inc_22",
    date: "2026-05-15",
    type: HeadType.Income,
    headId: "inc_cme_delegate",
    headName: "CME Delegate Fees",
    amount: 105000,
    voucherNumber: "RV-26-005",
    description: "State Homoeopathy Symposium Delegate Registrations",
    chapterId: "calicut_city",
    chapterIdInput: "KL-KZ-CC01",
    chapterNameInput: "Calicut City",
    collectedBy: "Dr. Faisal Rahman",
    paidBy: "Northern Region Delegate Doctors",
    offeredAmount: 105000,
    paidAmount: 105000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "kerala_treas",
    createdAt: "2026-05-15T13:00:00Z",
  },
  {
    slNo: 23,
    id: "tx_inc_23",
    date: "2026-06-01",
    type: HeadType.Income,
    headId: "inc_member_ordinary",
    headName: "Membership - ordinary",
    amount: 5000,
    voucherNumber: "RV-26-006",
    description: "Spot Ordinary Membership Subscription Dues",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Dr. Joseph Kurian",
    paidByMemberId: "MEM-KRL-102",
    offeredAmount: 5000,
    paidAmount: 5000,
    balanceAmount: 0,
    paymentMode: "Cash",
    createdBy: "cochin_treasurer",
    createdAt: "2026-06-01T11:00:00Z",
  },
  {
    slNo: 24,
    id: "tx_inc_24",
    date: "2026-06-18",
    type: HeadType.Income,
    headId: "inc_coaching",
    headName: "Coaching programs",
    amount: 115000,
    voucherNumber: "RV-26-007",
    description: "MO Exam Online Preparatory Course Batch Fees",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    collectedBy: "Dr. Basheer",
    paidBy: "Coaching Enrolled Doctors",
    offeredAmount: 115000,
    paidAmount: 115000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2026-06-18T15:00:00Z",
  },

  // ==================== PAYMENTS / EXPENSES ====================
  {
    slNo: 25,
    id: "tx_exp_1",
    date: "2024-05-12",
    type: HeadType.Expense,
    headId: "exp_meeting",
    headName: "Meeting expense",
    amount: 4200,
    voucherNumber: "PV-24-101",
    description: "Executive Committee monthly meeting refreshments and venue",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    paidByExpense: "Dr. Basheer",
    paidTo: "Grand Hotel Catering",
    payableAmount: 4200,
    paidAmount: 4200,
    balanceAmount: 0,
    paymentMode: "Cash",
    createdBy: "cochin_treasurer",
    createdAt: "2024-05-12T19:30:00Z",
  },
  {
    slNo: 26,
    id: "tx_exp_2",
    date: "2024-07-28",
    type: HeadType.Expense,
    headId: "exp_printing",
    headName: "Printing",
    amount: 24000,
    voucherNumber: "PV-24-102",
    description: "CME Souvenir Booklets & Delegate Certificate Printing",
    chapterId: "aluva",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    paidByExpense: "Dr. Abraham Mathew",
    paidTo: "Cochin Offset Printers",
    payableAmount: 24000,
    paidAmount: 24000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "aluva_treasurer",
    createdAt: "2024-07-28T16:00:00Z",
  },
  {
    slNo: 27,
    id: "tx_exp_3",
    date: "2024-10-15",
    type: HeadType.Expense,
    headId: "exp_digital_media",
    headName: "Digital media",
    amount: 16000,
    voucherNumber: "PV-24-103",
    description: "Official Website Annual Renewal, SSL & Server Hosting",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    paidByExpense: "Dr. Basheer",
    paidTo: "WebTech Solutions Cochin",
    payableAmount: 16000,
    paidAmount: 16000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2024-10-15T11:00:00Z",
  },
  {
    slNo: 28,
    id: "tx_exp_4",
    date: "2025-02-18",
    type: HeadType.Expense,
    headId: "exp_tada",
    headName: "TA&DA",
    amount: 18500,
    voucherNumber: "PV-25-101",
    description: "Travel Allowance for delegates attending Central Executive Meet",
    chapterId: "calicut_city",
    chapterIdInput: "KL-KZ-CC01",
    chapterNameInput: "Calicut City",
    paidByExpense: "Dr. Faisal Rahman",
    paidTo: "Dr. Sujith Kumar & Delegates",
    payableAmount: 18500,
    paidAmount: 18500,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "kerala_treas",
    createdAt: "2025-02-18T14:00:00Z",
  },
  {
    slNo: 29,
    id: "tx_exp_5",
    date: "2025-05-02",
    type: HeadType.Expense,
    headId: "exp_meeting",
    headName: "Meeting expense",
    amount: 3800,
    voucherNumber: "PV-25-102",
    description: "Executive Committee meeting tea & snacks charges",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    paidByExpense: "Dr. Basheer",
    paidTo: "Indian Coffee House",
    payableAmount: 3800,
    paidAmount: 3800,
    balanceAmount: 0,
    paymentMode: "Cash",
    createdBy: "cochin_treasurer",
    createdAt: "2025-05-02T18:30:00Z",
  },
  {
    slNo: 30,
    id: "tx_exp_6",
    date: "2025-08-25",
    type: HeadType.Expense,
    headId: "exp_digital_media",
    headName: "Digital media",
    amount: 48000,
    voucherNumber: "PV-25-103",
    description: "IHMA FinApp Mobile App Development Upgrade Charges",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    paidByExpense: "Dr. Basheer",
    paidTo: "AppCraft Tech Labs",
    payableAmount: 48000,
    paidAmount: 48000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2025-08-25T15:45:00Z",
  },
  {
    slNo: 31,
    id: "tx_exp_7",
    date: "2025-11-30",
    type: HeadType.Expense,
    headId: "exp_postage",
    headName: "Postage",
    amount: 3600,
    voucherNumber: "PV-25-104",
    description: "Courier charges for dispatching quarterly medical journal",
    chapterId: "chennai_central",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    paidByExpense: "Dr. R. Ramanujan",
    paidTo: "DTDC Courier Services",
    payableAmount: 3600,
    paidAmount: 3600,
    balanceAmount: 0,
    paymentMode: "Cash",
    createdBy: "chennai_treasurer",
    createdAt: "2025-11-30T12:00:00Z",
  },
  {
    slNo: 32,
    id: "tx_exp_8",
    date: "2026-02-15",
    type: HeadType.Expense,
    headId: "exp_cme_venue",
    headName: "CME Venue & Catering",
    amount: 35000,
    voucherNumber: "PV-26-101",
    description: "Auditorium hall rental & buffet lunch for CME Masterclass",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    paidByExpense: "Dr. Basheer",
    paidTo: "IMA Hall Management Ernakulam",
    payableAmount: 35000,
    paidAmount: 35000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "cochin_treasurer",
    createdAt: "2026-02-15T17:00:00Z",
  },
  {
    slNo: 33,
    id: "tx_exp_9",
    date: "2026-04-20",
    type: HeadType.Expense,
    headId: "exp_office_maint",
    headName: "Office Maintenance",
    amount: 5200,
    voucherNumber: "PV-26-102",
    description: "Annual accounting ledger registers & stationeries purchase",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    paidByExpense: "Dr. Basheer",
    paidTo: "National Stationers Ernakulam",
    payableAmount: 5200,
    paidAmount: 5200,
    balanceAmount: 0,
    paymentMode: "Cash",
    createdBy: "cochin_treasurer",
    createdAt: "2026-04-20T11:15:00Z",
  },
  {
    slNo: 34,
    id: "tx_exp_10",
    date: "2026-06-10",
    type: HeadType.Expense,
    headId: "exp_digital_media",
    headName: "Digital media",
    amount: 14000,
    voucherNumber: "PV-26-103",
    description: "Social media publicity posters & digital banners for CME",
    chapterId: "aluva",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    paidByExpense: "Dr. Abraham Mathew",
    paidTo: "Pixel Design Studio",
    payableAmount: 14000,
    paidAmount: 14000,
    balanceAmount: 0,
    paymentMode: "Bank",
    createdBy: "aluva_treasurer",
    createdAt: "2026-06-10T14:00:00Z",
  },

  // ==================== LOAN DISBURSEMENTS & REPAYMENTS ====================
  {
    slNo: 35,
    id: "tx_loan_1",
    date: "2024-06-15",
    type: HeadType.Loan,
    headId: "loan",
    headName: "Loan",
    amount: 100000,
    voucherNumber: "LN-24-301",
    description: "Temporary event organizational loan advance to Aluva Chapter",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    paidToCategory: "chapter",
    paidTo: "Aluva Chapter",
    paidToId: "KL-EK-AL02",
    paidToName: "Aluva Chapter",
    particulars: "CME Hall Booking advance loan",
    paymentMode: "Bank",
    amountReturned: 100000,
    loanBalance: 0,
    loanReturnDate: "2024-11-30",
    loanReturnedDate: "2024-11-20",
    repaymentPaymentMode: "Bank",
    repaymentDate: "2024-11-20",
    remarks: "Repaid ₹100000 via Bank on 20-11-2024: Full settlement received via RTGS",
    createdBy: "cochin_treasurer",
    createdAt: "2024-06-15T11:00:00Z",
  },
  {
    slNo: 36,
    id: "tx_loan_2",
    date: "2025-02-10",
    type: HeadType.Loan,
    headId: "loan",
    headName: "Loan",
    amount: 150000,
    voucherNumber: "LN-25-302",
    description: "State Homeo Conference venue booking advance loan",
    chapterId: "cochin",
    chapterIdInput: "KL-EK-CO01",
    chapterNameInput: "Cochin Chapter",
    paidToCategory: "chapter",
    paidTo: "Cochin Chapter",
    paidToId: "KL-EK-CO01",
    paidToName: "Cochin Chapter",
    particulars: "Conference Auditorium booking advance loan",
    paymentMode: "Bank",
    amountReturned: 100000,
    loanBalance: 50000,
    loanReturnDate: "2025-09-30",
    loanReturnedDate: "2025-06-15",
    repaymentPaymentMode: "Bank",
    repaymentDate: "2025-06-15",
    remarks: "Repaid ₹100000 via Bank on 15-06-2025: First installment received via NEFT",
    createdBy: "cochin_treasurer",
    createdAt: "2025-02-10T10:00:00Z",
  },
  {
    slNo: 37,
    id: "tx_loan_3",
    date: "2025-08-12",
    type: HeadType.Loan,
    headId: "loan",
    headName: "Loan",
    amount: 80000,
    voucherNumber: "LN-25-303",
    description: "Free Medical Camp Medicine stock advance loan",
    chapterId: "calicut_city",
    chapterIdInput: "KL-KZ-CC01",
    chapterNameInput: "Calicut City",
    paidToCategory: "chapter",
    paidTo: "Calicut City",
    paidToId: "KL-KZ-CC01",
    paidToName: "Calicut City",
    particulars: "Medicine stock procurement advance",
    paymentMode: "Bank",
    amountReturned: 40000,
    loanBalance: 40000,
    loanReturnDate: "2026-03-31",
    loanReturnedDate: "2025-12-01",
    repaymentPaymentMode: "Bank",
    repaymentDate: "2025-12-01",
    remarks: "Repaid ₹40000 via Bank on 01-12-2025: Partial repayment received",
    createdBy: "kerala_treas",
    createdAt: "2025-08-12T14:00:00Z",
  },
  {
    slNo: 38,
    id: "tx_loan_4",
    date: "2026-01-20",
    type: HeadType.Loan,
    headId: "loan",
    headName: "Loan",
    amount: 120000,
    voucherNumber: "LN-26-304",
    description: "Regional Journal Printing advance loan to Chennai Central",
    chapterId: "chennai_central",
    chapterIdInput: "TN-CN-CC01",
    chapterNameInput: "Chennai Central",
    paidToCategory: "chapter",
    paidTo: "Chennai Central",
    paidToId: "TN-CN-CC01",
    paidToName: "Chennai Central",
    particulars: "Journal printing advance",
    paymentMode: "Bank",
    amountReturned: 50000,
    loanBalance: 70000,
    loanReturnDate: "2026-08-31",
    loanReturnedDate: "2026-04-10",
    repaymentPaymentMode: "Cash",
    repaymentDate: "2026-04-10",
    remarks: "Repaid ₹50000 via Cash on 10-04-2026: Cash repayment handed over at state meet",
    createdBy: "chennai_treasurer",
    createdAt: "2026-01-20T11:00:00Z",
  },
  {
    slNo: 39,
    id: "tx_loan_5",
    date: "2026-05-10",
    type: HeadType.Loan,
    headId: "loan",
    headName: "Loan",
    amount: 50000,
    voucherNumber: "LN-26-305",
    description: "Emergency clinic renovation loan advance",
    chapterId: "aluva",
    chapterIdInput: "KL-EK-AL02",
    chapterNameInput: "Aluva Chapter",
    paidToCategory: "chapter",
    paidTo: "Aluva Chapter",
    paidToId: "KL-EK-AL02",
    paidToName: "Aluva Chapter",
    particulars: "Chapter office building repair advance",
    paymentMode: "Cash",
    amountReturned: 20000,
    loanBalance: 30000,
    loanReturnDate: "2026-10-31",
    loanReturnedDate: "2026-06-15",
    repaymentPaymentMode: "Cash",
    repaymentDate: "2026-06-15",
    remarks: "Repaid ₹20000 via Cash on 15-06-2026: First cash installment received",
    createdBy: "aluva_treasurer",
    createdAt: "2026-05-10T12:00:00Z",
  },
  // FY 2026-27: month-by-month sample activity for richer reports and repayment tracking.
  ...[
    ["2026-07-12", HeadType.Income, "inc_member_gold", "Membership - Gold", 72000, "cochin", "KL-EK-CO01", "Cochin Chapter"],
    ["2026-08-18", HeadType.Expense, "exp_meeting", "Meeting expense", 46500, "cochin", "KL-EK-CO01", "Cochin Chapter"],
    ["2026-09-09", HeadType.Income, "inc_donations", "Donations", 56000, "aluva", "KL-EK-AL02", "Aluva Chapter"],
    ["2026-10-21", HeadType.Expense, "exp_printing", "Printing", 18200, "aluva", "KL-EK-AL02", "Aluva Chapter"],
    ["2026-11-14", HeadType.Income, "inc_coaching", "Coaching programs", 38500, "cochin", "KL-EK-CO01", "Cochin Chapter"],
    ["2026-12-16", HeadType.Expense, "exp_digital_media", "Digital media", 24500, "cochin", "KL-EK-CO01", "Cochin Chapter"],
    ["2027-01-11", HeadType.Income, "inc_sponsorship", "Sponsorship", 95000, "aluva", "KL-EK-AL02", "Aluva Chapter"],
    ["2027-02-20", HeadType.Expense, "exp_meeting", "Meeting expense", 12800, "cochin", "KL-EK-CO01", "Cochin Chapter"],
    ["2027-03-15", HeadType.Income, "inc_bank", "Bank income", 21500, "cochin", "KL-EK-CO01", "Cochin Chapter"],
  ].map(([date, type, headId, headName, amount, chapterId, chapterIdInput, chapterNameInput], index) => ({
    id: `tx_2026_27_${index + 1}`,
    slNo: 100 + index,
    date: date as string,
    type: type as HeadType,
    headId: headId as string,
    headName: headName as string,
    amount: amount as number,
    voucherNumber: `FY26-${String(index + 1).padStart(3, "0")}`,
    chapterId: chapterId as string,
    chapterIdInput: chapterIdInput as string,
    chapterNameInput: chapterNameInput as string,
    paymentMode: index % 2 === 0 ? "Bank" as const : "Cash" as const,
    paidAmount: amount as number,
    createdBy: chapterId === "cochin" ? "cochin_treasurer" : "aluva_treasurer",
    createdAt: `${date as string}T10:00:00Z`,
  })),
  {
    id: "tx_loan_2026_27_cochin", slNo: 110, date: "2026-10-05", type: HeadType.Loan, headId: "loan", headName: "Loan", amount: 100000,
    voucherNumber: "LN-26-101", chapterId: "cochin", chapterIdInput: "KL-EK-CO01", chapterNameInput: "Cochin Chapter", paidToCategory: "chapter", paidTo: "Cochin Chapter", paidToId: "KL-EK-CO01", paidToName: "Cochin Chapter", particulars: "CME equipment advance", paymentMode: "Bank", amountReturned: 40000, loanBalance: 60000, loanReturnDate: "2027-03-31", loanReturnedDate: "2027-01-25", repaymentPaymentMode: "Bank", repaymentDate: "2027-01-25", remarks: "First repayment received", createdBy: "cochin_treasurer", createdAt: "2026-10-05T10:00:00Z"
  },
  {
    id: "tx_loan_2026_27_aluva", slNo: 111, date: "2026-12-08", type: HeadType.Loan, headId: "loan", headName: "Loan", amount: 75000,
    voucherNumber: "LN-26-102", chapterId: "aluva", chapterIdInput: "KL-EK-AL02", chapterNameInput: "Aluva Chapter", paidToCategory: "chapter", paidTo: "Aluva Chapter", paidToId: "KL-EK-AL02", paidToName: "Aluva Chapter", particulars: "Chapter office repairs", paymentMode: "Cash", amountReturned: 25000, loanBalance: 50000, loanReturnDate: "2027-04-30", loanReturnedDate: "2027-03-10", repaymentPaymentMode: "Cash", repaymentDate: "2027-03-10", remarks: "Partial repayment received", createdBy: "aluva_treasurer", createdAt: "2026-12-08T10:00:00Z"
  },
];

// Database Management Helpers
export function loadDatabase() {
  const users = localStorage.getItem("ihma_users");
  const accountHeads = localStorage.getItem("ihma_account_heads");
  const transactions = localStorage.getItem("ihma_transactions");
  const assets = localStorage.getItem("ihma_assets");
  const bankBalances = localStorage.getItem("ihma_bank_balances");
  const chapterDirectory = localStorage.getItem("ihma_chapter_directory");
  const members = localStorage.getItem("ihma_members");
  const dbVersion = localStorage.getItem("ihma_db_version");

  if (
    !users ||
    !accountHeads ||
    !transactions ||
    !assets ||
    !bankBalances ||
    !chapterDirectory ||
    !members ||
    dbVersion !== CURRENT_DB_VERSION
  ) {
    // Initialize defaults
    localStorage.setItem("ihma_db_version", CURRENT_DB_VERSION);
    localStorage.setItem("ihma_users", JSON.stringify(USERS));
    localStorage.setItem("ihma_account_heads", JSON.stringify(DEFAULT_ACCOUNT_HEADS));
    localStorage.setItem("ihma_transactions", JSON.stringify(PRELOADED_TRANSACTIONS));
    localStorage.setItem("ihma_assets", JSON.stringify(PRELOADED_ASSETS));
    localStorage.setItem("ihma_bank_balances", JSON.stringify(PRELOADED_BANK_BALANCES));
    localStorage.setItem("ihma_chapter_directory", JSON.stringify(PRELOADED_CHAPTER_DIRECTORY));
    localStorage.setItem("ihma_members", JSON.stringify(PRELOADED_MEMBERS));

    return {
      users: USERS,
      accountHeads: DEFAULT_ACCOUNT_HEADS,
      transactions: PRELOADED_TRANSACTIONS,
      assets: PRELOADED_ASSETS,
      bankBalances: PRELOADED_BANK_BALANCES,
      chapterDirectory: PRELOADED_CHAPTER_DIRECTORY,
      members: PRELOADED_MEMBERS,
    };
  }

  // Add newly introduced demo records without replacing any locally entered data.
  // Remove the two retired seeded expense heads and their old sample entries.
  const retiredHeadIds = new Set([
    "exp_cme_venue",
    "exp_office_maint",
    "inc_cme_delegate",
    "inc_trust_grant",
  ]);
  const savedHeads = JSON.parse(accountHeads) as AccountHead[];
  const savedTransactions = JSON.parse(transactions) as Transaction[];
  const mergedHeads = [
    ...DEFAULT_ACCOUNT_HEADS,
    ...savedHeads.filter((head) => !retiredHeadIds.has(head.id) && !DEFAULT_ACCOUNT_HEADS.some((defaultHead) => defaultHead.id === head.id)),
  ];
  const seedTransactions = PRELOADED_TRANSACTIONS.filter((tx) => !retiredHeadIds.has(tx.headId));
  const mergedTransactions = [
    ...seedTransactions.filter((seed) => !savedTransactions.some((saved) => saved.id === seed.id)),
    ...savedTransactions.filter((tx) => !retiredHeadIds.has(tx.headId)),
  ];

  localStorage.setItem("ihma_account_heads", JSON.stringify(mergedHeads));
  localStorage.setItem("ihma_transactions", JSON.stringify(mergedTransactions));

  return {
    users: JSON.parse(users),
    accountHeads: mergedHeads,
    transactions: mergedTransactions,
    assets: JSON.parse(assets),
    bankBalances: JSON.parse(bankBalances),
    chapterDirectory: JSON.parse(chapterDirectory),
    members: JSON.parse(members),
  };
}

export function saveDatabase(data: {
  users: User[];
  accountHeads: AccountHead[];
  transactions: Transaction[];
  assets: Asset[];
  bankBalances: BankBalance[];
  chapterDirectory: ChapterMaster[];
  members: Member[];
}) {
  localStorage.setItem("ihma_db_version", CURRENT_DB_VERSION);
  localStorage.setItem("ihma_users", JSON.stringify(data.users));
  localStorage.setItem("ihma_account_heads", JSON.stringify(data.accountHeads));
  localStorage.setItem("ihma_transactions", JSON.stringify(data.transactions));
  localStorage.setItem("ihma_assets", JSON.stringify(data.assets));
  localStorage.setItem("ihma_bank_balances", JSON.stringify(data.bankBalances));
  localStorage.setItem("ihma_chapter_directory", JSON.stringify(data.chapterDirectory));
  localStorage.setItem("ihma_members", JSON.stringify(data.members));
}

export function resetToDefaults() {
  localStorage.setItem("ihma_db_version", CURRENT_DB_VERSION);
  localStorage.setItem("ihma_users", JSON.stringify(USERS));
  localStorage.setItem("ihma_account_heads", JSON.stringify(DEFAULT_ACCOUNT_HEADS));
  localStorage.setItem("ihma_transactions", JSON.stringify(PRELOADED_TRANSACTIONS));
  localStorage.setItem("ihma_assets", JSON.stringify(PRELOADED_ASSETS));
  localStorage.setItem("ihma_bank_balances", JSON.stringify(PRELOADED_BANK_BALANCES));
  localStorage.setItem("ihma_chapter_directory", JSON.stringify(PRELOADED_CHAPTER_DIRECTORY));
  localStorage.setItem("ihma_members", JSON.stringify(PRELOADED_MEMBERS));

  return {
    users: USERS,
    accountHeads: DEFAULT_ACCOUNT_HEADS,
    transactions: PRELOADED_TRANSACTIONS,
    assets: PRELOADED_ASSETS,
    bankBalances: PRELOADED_BANK_BALANCES,
    chapterDirectory: PRELOADED_CHAPTER_DIRECTORY,
    members: PRELOADED_MEMBERS,
  };
}
